-- 초기 시드 데이터 (개발/데모용). 매 기동 시 재실행되지만 INSERT IGNORE라 기존 행은 건드리지 않는다.
-- (dev: ddl-auto=create-drop이라 항상 빈 테이블에 새로 들어감 / prod: ddl-auto=update라 최초 1회만 실제로 삽입됨)
-- 문자 인덱스(start_index/end_index)는 UTF-16 코드유닛 기준, 0-based, end exclusive.

-- words
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (1, '食べる', 'たべる', '먹다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (2, '飲む', 'のむ', '마시다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (3, '見る', 'みる', '보다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (4, '聞く', 'きく', '듣다/묻다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (5, '行く', 'いく', '가다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (6, '来る', 'くる', '오다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (7, '学校', 'がっこう', '학교', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (8, '先生', 'せんせい', '선생님', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (9, '学生', 'がくせい', '학생', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (10, '友達', 'ともだち', '친구', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (11, '本', 'ほん', '책', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (12, '水', 'みず', '물', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (13, '野菜', 'やさい', '야채', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (14, '果物', 'くだもの', '과일', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (15, '大きい', 'おおきい', '크다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (16, '小さい', 'ちいさい', '작다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (17, '新しい', 'あたらしい', '새롭다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (18, '高い', 'たかい', '비싸다/높다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (19, '毎日', 'まいにち', '매일', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (20, '今日', 'きょう', '오늘', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (21, '勉強する', 'べんきょうする', '공부하다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (22, '仕事', 'しごと', '일/업무', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (23, '電車', 'でんしゃ', '전철', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (24, '元気だ', 'げんきだ', '건강하다/활기차다', 'N4', 'な형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (25, '大学', 'だいがく', '대학교', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (26, '会社', 'かいしゃ', '회사', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (27, '家', 'いえ', '집', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (28, '部屋', 'へや', '방', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (29, '車', 'くるま', '자동차', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (30, '自転車', 'じてんしゃ', '자전거', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (31, '天気', 'てんき', '날씨', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (32, '雨', 'あめ', '비', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (33, '雪', 'ゆき', '눈', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (34, '朝', 'あさ', '아침', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (35, '夜', 'よる', '밤', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (36, '今', 'いま', '지금', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (37, '時間', 'じかん', '시간', 'N5', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (38, '買う', 'かう', '사다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (39, '売る', 'うる', '팔다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (40, '読む', 'よむ', '읽다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (41, '書く', 'かく', '쓰다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (42, '話す', 'はなす', '말하다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (43, '立つ', 'たつ', '서다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (44, '座る', 'すわる', '앉다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (45, '寝る', 'ねる', '자다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (46, '起きる', 'おきる', '일어나다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (47, '休む', 'やすむ', '쉬다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (48, '走る', 'はしる', '달리다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (49, '泳ぐ', 'およぐ', '수영하다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (50, '歌う', 'うたう', '노래하다', 'N5', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (51, '甘い', 'あまい', '달다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (52, '辛い', 'からい', '맵다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (53, '暑い', 'あつい', '덥다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (54, '寒い', 'さむい', '춥다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (55, '忙しい', 'いそがしい', '바쁘다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (56, '楽しい', 'たのしい', '즐겁다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (57, '難しい', 'むずかしい', '어렵다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (58, '易しい', 'やさしい', '쉽다', 'N5', 'い형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (59, '静かだ', 'しずかだ', '조용하다', 'N5', 'な형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (60, '有名だ', 'ゆうめいだ', '유명하다', 'N5', 'な형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (61, '便利だ', 'べんりだ', '편리하다', 'N5', 'な형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (62, '親切だ', 'しんせつだ', '친절하다', 'N5', 'な형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (63, '経験', 'けいけん', '경험', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (64, '準備', 'じゅんび', '준비', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (65, '説明', 'せつめい', '설명', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (66, '質問', 'しつもん', '질문', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (67, '予定', 'よてい', '예정', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (68, '会議', 'かいぎ', '회의', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (69, '連絡', 'れんらく', '연락', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (70, '練習', 'れんしゅう', '연습', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (71, '参加', 'さんか', '참가', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (72, '到着', 'とうちゃく', '도착', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (73, '出発', 'しゅっぱつ', '출발', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (74, '決める', 'きめる', '정하다', 'N4', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (75, '続ける', 'つづける', '계속하다', 'N4', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (76, '始まる', 'はじまる', '시작되다', 'N4', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (77, '終わる', 'おわる', '끝나다', 'N4', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (78, '変える', 'かえる', '바꾸다', 'N4', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (79, '覚える', 'おぼえる', '외우다', 'N4', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (80, '忘れる', 'わすれる', '잊다', 'N4', '동사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (81, '気持ち', 'きもち', '기분/느낌', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (82, '性格', 'せいかく', '성격', 'N4', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (83, '危険だ', 'きけんだ', '위험하다', 'N4', 'な형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (84, '安全だ', 'あんぜんだ', '안전하다', 'N4', 'な형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (85, '環境', 'かんきょう', '환경', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (86, '経済', 'けいざい', '경제', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (87, '政治', 'せいじ', '정치', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (88, '社会', 'しゃかい', '사회', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (89, '文化', 'ぶんか', '문화', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (90, '歴史', 'れきし', '역사', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (91, '影響', 'えいきょう', '영향', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (92, '原因', 'げんいん', '원인', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (93, '結果', 'けっか', '결과', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (94, '解決', 'かいけつ', '해결', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (95, '発展', 'はってん', '발전', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (96, '増加', 'ぞうか', '증가', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (97, '減少', 'げんしょう', '감소', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (98, '判断', 'はんだん', '판단', 'N3', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (99, '傾向', 'けいこう', '경향', 'N2', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (100, '手段', 'しゅだん', '수단', 'N2', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (101, '概念', 'がいねん', '개념', 'N2', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (102, '分野', 'ぶんや', '분야', 'N2', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (103, '現象', 'げんしょう', '현상', 'N2', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (104, '要素', 'ようそ', '요소', 'N2', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (105, '前提', 'ぜんてい', '전제', 'N2', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (106, '矛盾', 'むじゅん', '모순', 'N2', '명사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (107, '抽象的だ', 'ちゅうしょうてきだ', '추상적이다', 'N1', 'な형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (108, '曖昧だ', 'あいまいだ', '애매하다', 'N1', 'な형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (109, '顕著だ', 'けんちょだ', '현저하다', 'N1', 'な형용사', NOW());
INSERT IGNORE INTO words (id, expression, furigana, meaning, level, part_of_speech, created_at) VALUES (110, '緻密だ', 'ちみつだ', '치밀하다', 'N1', 'な형용사', NOW());

-- example_sentences
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (1, 1, '彼は毎日野菜を食べる。', 'かれはまいにちやさいをたべる。', '그는 매일 야채를 먹는다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (2, 2, '私は毎日水を飲む。', 'わたしはまいにちみずをのむ。', '나는 매일 물을 마신다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (3, 3, '学生は本を見る。', 'がくせいはほんをみる。', '학생은 책을 본다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (4, 4, '学生は先生の話を聞く。', 'がくせいはせんせいのはなしをきく。', '학생은 선생님의 이야기를 듣는다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (5, 5, '友達と学校へ行く。', 'ともだちとがっこうへいく。', '친구와 학교에 간다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (6, 6, '先生が学校に来る。', 'せんせいががっこうにくる。', '선생님이 학교에 온다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (7, 7, '毎日学校へ行く。', 'まいにちがっこうへいく。', '매일 학교에 간다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (8, 8, '先生はとても元気だ。', 'せんせいはとてもげんきだ。', '선생님은 매우 건강하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (9, 9, '学生は毎日勉強する。', 'がくせいはまいにちべんきょうする。', '학생은 매일 공부한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (10, 10, '友達は電車で来る。', 'ともだちはでんしゃでくる。', '친구는 전철로 온다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (11, 11, 'この本はとても大きい。', 'このほんはとてもおおきい。', '이 책은 매우 크다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (12, 12, '水を飲む。', 'みずをのむ。', '물을 마신다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (13, 13, '私は野菜が好きだ。', 'わたしはやさいがすきだ。', '나는 야채를 좋아한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (14, 14, '果物を食べる。', 'くだものをたべる。', '과일을 먹는다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (15, 15, 'この学校はとても大きい。', 'このがっこうはとてもおおきい。', '이 학교는 매우 크다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (16, 16, 'この本は小さい。', 'このほんはちいさい。', '이 책은 작다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (17, 17, '新しい先生が来る。', 'あたらしいせんせいがくる。', '새로운 선생님이 온다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (18, 18, 'この果物は高い。', 'このくだものはたかい。', '이 과일은 비싸다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (19, 19, '毎日学校で勉強する。', 'まいにちがっこうでべんきょうする。', '매일 학교에서 공부한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (20, 20, '今日は学校が休みだ。', 'きょうはがっこうがやすみだ。', '오늘은 학교가 쉬는 날이다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (21, 21, '学生は毎日教室で勉強する。', 'がくせいはまいにちきょうしつでべんきょうする。', '학생은 매일 교실에서 공부한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (22, 22, '父は毎日仕事に行く。', 'ちちはまいにちしごとにいく。', '아버지는 매일 일하러 간다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (23, 23, '電車で学校へ行く。', 'でんしゃでがっこうへいく。', '전철로 학교에 간다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (24, 24, '先生はいつも元気だ。', 'せんせいはいつもげんきだ。', '선생님은 항상 건강하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (25, 25, '兄は毎日会社へ行く。', 'あにはまいにちかいしゃへいく。', '형/오빠는 매일 회사에 간다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (26, 26, '彼女は大学で経済を勉強する。', 'かのじょはだいがくでけいざいをべんきょうする。', '그녀는 대학에서 경제를 공부한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (27, 27, '家で本を読む。', 'いえでほんをよむ。', '집에서 책을 읽는다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (28, 28, '部屋はとても小さい。', 'へやはとてもちいさい。', '방은 매우 작다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (29, 29, '車で学校へ行く。', 'くるまでがっこうへいく。', '자동차로 학교에 간다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (30, 30, '自転車で友達の家へ行く。', 'じてんしゃでともだちのいえへいく。', '자전거로 친구 집에 간다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (31, 31, '今日は天気がいい。', 'きょうはてんきがいい。', '오늘은 날씨가 좋다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (32, 32, '今日は雨だ。', 'きょうはあめだ。', '오늘은 비가 온다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (33, 33, '今日は雪だ。', 'きょうはゆきだ。', '오늘은 눈이 온다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (34, 34, '朝は忙しい。', 'あさはいそがしい。', '아침은 바쁘다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (35, 35, '夜は静かだ。', 'よるはしずかだ。', '밤은 조용하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (36, 36, '今、忙しい。', 'いま、いそがしい。', '지금 바쁘다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (37, 37, '時間がない。', 'じかんがない。', '시간이 없다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (38, 38, '新しい本を買う。', 'あたらしいほんをかう。', '새 책을 산다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (39, 39, '友達に本を売る。', 'ともだちにほんをうる。', '친구에게 책을 판다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (40, 40, '学生は毎日本を読む。', 'がくせいはまいにちほんをよむ。', '학생은 매일 책을 읽는다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (41, 41, '学生は本に名前を書く。', 'がくせいはほんになまえをかく。', '학생은 책에 이름을 쓴다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (42, 42, '先生と話す。', 'せんせいとはなす。', '선생님과 이야기한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (43, 43, '学生が立つ。', 'がくせいがたつ。', '학생이 선다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (44, 44, '先生の前に座る。', 'せんせいのまえにすわる。', '선생님 앞에 앉는다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (45, 45, '夜早く寝る。', 'よるはやくねる。', '밤에 일찍 잔다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (46, 46, '朝早く起きる。', 'あさはやくおきる。', '아침에 일찍 일어난다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (47, 47, '今日は仕事を休む。', 'きょうはしごとをやすむ。', '오늘은 일을 쉰다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (48, 48, '学生は毎日走る。', 'がくせいはまいにちはしる。', '학생은 매일 달린다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (49, 49, '友達と泳ぐ。', 'ともだちとおよぐ。', '친구와 수영한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (50, 50, '友達と歌う。', 'ともだちとうたう。', '친구와 노래한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (51, 51, 'この果物は甘い。', 'このくだものはあまい。', '이 과일은 달다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (52, 52, 'この野菜は辛い。', 'このやさいはからい。', '이 야채는 맵다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (53, 53, '今日はとても暑い。', 'きょうはとてもあつい。', '오늘은 매우 덥다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (54, 54, '今日は寒い。', 'きょうはさむい。', '오늘은 춥다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (55, 55, '先生は毎日忙しい。', 'せんせいはまいにちいそがしい。', '선생님은 매일 바쁘다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (56, 56, '学校はとても楽しい。', 'がっこうはとてもたのしい。', '학교는 매우 즐겁다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (57, 57, 'この本は難しい。', 'このほんはむずかしい。', '이 책은 어렵다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (58, 58, 'この本は易しい。', 'このほんはやさしい。', '이 책은 쉽다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (59, 59, 'この部屋は静かだ。', 'このへやはしずかだ。', '이 방은 조용하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (60, 60, 'この学校は有名だ。', 'このがっこうはゆうめいだ。', '이 학교는 유명하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (61, 61, '電車は便利だ。', 'でんしゃはべんりだ。', '전철은 편리하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (62, 62, '先生はとても親切だ。', 'せんせいはとてもしんせつだ。', '선생님은 매우 친절하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (63, 63, 'いい経験になる。', 'いいけいけんになる。', '좋은 경험이 된다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (64, 64, '会議の準備をする。', 'かいぎのじゅんびをする。', '회의 준비를 한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (65, 65, '先生が説明する。', 'せんせいがせつめいする。', '선생님이 설명한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (66, 66, '学生が質問する。', 'がくせいがしつもんする。', '학생이 질문한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (67, 67, '会議の予定を決める。', 'かいぎのよていをきめる。', '회의 예정을 정한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (68, 68, '今日は会議がある。', 'きょうはかいぎがある。', '오늘은 회의가 있다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (69, 69, '友達に連絡する。', 'ともだちにれんらくする。', '친구에게 연락한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (70, 70, '毎日練習する。', 'まいにちれんしゅうする。', '매일 연습한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (71, 71, '会議に参加する。', 'かいぎにさんかする。', '회의에 참가한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (72, 72, '電車が到着する。', 'でんしゃがとうちゃくする。', '전철이 도착한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (73, 73, '朝早く出発する。', 'あさはやくしゅっぱつする。', '아침 일찍 출발한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (74, 74, '予定を決める。', 'よていをきめる。', '예정을 정한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (75, 75, '毎日勉強を続ける。', 'まいにちべんきょうをつづける。', '매일 공부를 계속한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (76, 76, '会議が始まる。', 'かいぎがはじまる。', '회의가 시작된다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (77, 77, '会議が終わる。', 'かいぎがおわる。', '회의가 끝난다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (78, 78, '予定を変える。', 'よていをかえる。', '예정을 바꾼다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (79, 79, '毎日新しい単語を覚える。', 'まいにちあたらしいたんごをおぼえる。', '매일 새로운 단어를 외운다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (80, 80, '彼はよく忘れる。', 'かれはよくわすれる。', '그는 자주 잊는다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (81, 81, 'いい気持ちだ。', 'いいきもちだ。', '좋은 기분이다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (82, 82, '彼女の性格は親切だ。', 'かのじょのせいかくはしんせつだ。', '그녀의 성격은 친절하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (83, 83, 'この仕事は危険だ。', 'このしごとはきけんだ。', '이 일은 위험하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (84, 84, 'この電車は安全だ。', 'このでんしゃはあんぜんだ。', '이 전철은 안전하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (85, 85, '環境について先生と話す。', 'かんきょうについてせんせいとはなす。', '환경에 대해 선생님과 이야기한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (86, 86, '大学で経済を勉強する。', 'だいがくでけいざいをべんきょうする。', '대학에서 경제를 공부한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (87, 87, '政治は難しい。', 'せいじはむずかしい。', '정치는 어렵다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (88, 88, '学校も社会の一部だ。', 'がっこうもしゃかいのいちぶだ。', '학교도 사회의 일부다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (89, 89, '文化を勉強する。', 'ぶんかをべんきょうする。', '문화를 공부한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (90, 90, '歴史を勉強する。', 'れきしをべんきょうする。', '역사를 공부한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (91, 91, '天気は気持ちに影響する。', 'てんきはきもちにえいきょうする。', '날씨는 기분에 영향을 준다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (92, 92, '原因を説明する。', 'げんいんをせつめいする。', '원인을 설명한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (93, 93, '会議の結果を説明する。', 'かいぎのけっかをせつめいする。', '회의 결과를 설명한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (94, 94, '原因を解決する。', 'げんいんをかいけつする。', '원인을 해결한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (95, 95, '経済が発展する。', 'けいざいがはってんする。', '경제가 발전한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (96, 96, '学生が増加する。', 'がくせいがぞうかする。', '학생이 증가한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (97, 97, '学生が減少する。', 'がくせいがげんしょうする。', '학생이 감소한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (98, 98, '先生が判断する。', 'せんせいがはんだんする。', '선생님이 판단한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (99, 99, '学生が増加する傾向がある。', 'がくせいがぞうかするけいこうがある。', '학생이 증가하는 경향이 있다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (100, 100, '電車は便利な手段だ。', 'でんしゃはべんりなしゅだんだ。', '전철은 편리한 수단이다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (101, 101, '難しい概念を説明する。', 'むずかしいがいねんをせつめいする。', '어려운 개념을 설명한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (102, 102, '経済の分野を勉強する。', 'けいざいのぶんやをべんきょうする。', '경제 분야를 공부한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (103, 103, '環境の現象を説明する。', 'かんきょうのげんしょうをせつめいする。', '환경 현상을 설명한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (104, 104, '経済は重要な要素だ。', 'けいざいはじゅうようなようそだ。', '경제는 중요한 요소다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (105, 105, '前提を説明する。', 'ぜんていをせつめいする。', '전제를 설명한다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (106, 106, '説明に矛盾がある。', 'せつめいにむじゅんがある。', '설명에 모순이 있다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (107, 107, 'この概念は抽象的だ。', 'このがいねんはちゅうしょうてきだ。', '이 개념은 추상적이다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (108, 108, '説明が曖昧だ。', 'せつめいがあいまいだ。', '설명이 애매하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (109, 109, '増加は顕著だ。', 'ぞうかはけんちょだ。', '증가는 현저하다.');
INSERT IGNORE INTO example_sentences (id, word_id, sentence_jp, sentence_reading, sentence_meaning) VALUES (110, 110, '説明はとても緻密だ。', 'せつめいはとてもちみつだ。', '설명은 매우 치밀하다.');

-- example_sentence_words (linked word spans)
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (1, 1, 19, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (2, 1, 13, 4, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (3, 1, 1, 7, 10);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (4, 2, 19, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (5, 2, 12, 4, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (6, 2, 2, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (7, 3, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (8, 3, 11, 3, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (9, 3, 3, 5, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (10, 4, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (11, 4, 8, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (12, 4, 4, 8, 10);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (13, 5, 10, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (14, 5, 7, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (15, 5, 5, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (16, 6, 8, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (17, 6, 7, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (18, 6, 6, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (19, 7, 19, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (20, 7, 7, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (21, 7, 5, 5, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (22, 8, 8, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (23, 8, 24, 6, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (24, 9, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (25, 9, 19, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (26, 9, 21, 5, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (27, 10, 10, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (28, 10, 23, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (29, 10, 6, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (30, 11, 11, 2, 3);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (31, 11, 15, 7, 10);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (32, 12, 12, 0, 1);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (33, 12, 2, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (34, 13, 13, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (35, 14, 14, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (36, 14, 1, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (37, 15, 7, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (38, 15, 15, 8, 11);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (39, 16, 11, 2, 3);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (40, 16, 16, 4, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (41, 17, 17, 0, 3);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (42, 17, 8, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (43, 17, 6, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (44, 18, 14, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (45, 18, 18, 5, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (46, 19, 19, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (47, 19, 7, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (48, 19, 21, 5, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (49, 20, 20, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (50, 20, 7, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (51, 21, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (52, 21, 19, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (53, 21, 21, 8, 12);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (54, 22, 19, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (55, 22, 22, 4, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (56, 22, 5, 7, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (57, 23, 23, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (58, 23, 7, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (59, 23, 5, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (60, 24, 8, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (61, 24, 24, 6, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (62, 25, 19, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (63, 25, 26, 4, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (64, 25, 5, 7, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (65, 26, 25, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (66, 26, 86, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (67, 26, 21, 9, 13);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (68, 27, 27, 0, 1);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (69, 27, 11, 2, 3);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (70, 27, 40, 4, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (71, 28, 28, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (72, 28, 16, 6, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (73, 29, 29, 0, 1);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (74, 29, 7, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (75, 29, 5, 5, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (76, 30, 30, 0, 3);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (77, 30, 10, 4, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (78, 30, 27, 7, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (79, 30, 5, 9, 11);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (80, 31, 20, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (81, 31, 31, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (82, 32, 20, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (83, 32, 32, 3, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (84, 33, 20, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (85, 33, 33, 3, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (86, 34, 34, 0, 1);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (87, 34, 55, 2, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (88, 35, 35, 0, 1);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (89, 35, 59, 2, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (90, 36, 36, 0, 1);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (91, 36, 55, 2, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (92, 37, 37, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (93, 38, 17, 0, 3);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (94, 38, 11, 3, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (95, 38, 38, 5, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (96, 39, 10, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (97, 39, 11, 3, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (98, 39, 39, 5, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (99, 40, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (100, 40, 19, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (101, 40, 11, 5, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (102, 40, 40, 7, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (103, 41, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (104, 41, 11, 3, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (105, 41, 41, 8, 10);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (106, 42, 8, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (107, 42, 42, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (108, 43, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (109, 43, 43, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (110, 44, 8, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (111, 44, 44, 5, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (112, 45, 35, 0, 1);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (113, 45, 45, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (114, 46, 34, 0, 1);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (115, 46, 46, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (116, 47, 20, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (117, 47, 22, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (118, 47, 47, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (119, 48, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (120, 48, 19, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (121, 48, 48, 5, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (122, 49, 10, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (123, 49, 49, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (124, 50, 10, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (125, 50, 50, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (126, 51, 14, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (127, 51, 51, 5, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (128, 52, 13, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (129, 52, 52, 5, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (130, 53, 20, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (131, 53, 53, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (132, 54, 20, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (133, 54, 54, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (134, 55, 8, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (135, 55, 19, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (136, 55, 55, 5, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (137, 56, 7, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (138, 56, 56, 6, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (139, 57, 11, 2, 3);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (140, 57, 57, 4, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (141, 58, 11, 2, 3);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (142, 58, 58, 4, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (143, 59, 28, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (144, 59, 59, 5, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (145, 60, 7, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (146, 60, 60, 5, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (147, 61, 23, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (148, 61, 61, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (149, 62, 8, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (150, 62, 62, 6, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (151, 63, 63, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (152, 64, 68, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (153, 64, 64, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (154, 65, 8, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (155, 65, 65, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (156, 66, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (157, 66, 66, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (158, 67, 68, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (159, 67, 67, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (160, 67, 74, 6, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (161, 68, 20, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (162, 68, 68, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (163, 69, 10, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (164, 69, 69, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (165, 70, 19, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (166, 70, 70, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (167, 71, 68, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (168, 71, 71, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (169, 72, 23, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (170, 72, 72, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (171, 73, 34, 0, 1);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (172, 73, 73, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (173, 74, 67, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (174, 74, 74, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (175, 75, 19, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (176, 75, 75, 5, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (177, 76, 68, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (178, 76, 76, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (179, 77, 68, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (180, 77, 77, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (181, 78, 67, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (182, 78, 78, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (183, 79, 19, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (184, 79, 17, 2, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (185, 79, 79, 8, 11);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (186, 80, 80, 4, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (187, 81, 81, 2, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (188, 82, 82, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (189, 82, 62, 6, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (190, 83, 22, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (191, 83, 83, 5, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (192, 84, 23, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (193, 84, 84, 5, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (194, 85, 85, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (195, 85, 8, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (196, 85, 42, 9, 11);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (197, 86, 25, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (198, 86, 86, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (199, 86, 21, 6, 10);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (200, 87, 87, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (201, 87, 57, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (202, 88, 7, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (203, 88, 88, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (204, 89, 89, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (205, 89, 21, 3, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (206, 90, 90, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (207, 90, 21, 3, 7);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (208, 91, 31, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (209, 91, 81, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (210, 91, 91, 7, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (211, 92, 92, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (212, 92, 65, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (213, 93, 68, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (214, 93, 93, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (215, 93, 65, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (216, 94, 92, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (217, 94, 94, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (218, 95, 86, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (219, 95, 95, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (220, 96, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (221, 96, 96, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (222, 97, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (223, 97, 97, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (224, 98, 8, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (225, 98, 98, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (226, 99, 9, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (227, 99, 96, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (228, 99, 99, 7, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (229, 100, 23, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (230, 100, 100, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (231, 101, 57, 0, 3);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (232, 101, 101, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (233, 101, 65, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (234, 102, 86, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (235, 102, 102, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (236, 102, 21, 6, 10);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (237, 103, 85, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (238, 103, 103, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (239, 103, 65, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (240, 104, 86, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (241, 104, 104, 6, 8);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (242, 105, 105, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (243, 105, 65, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (244, 106, 65, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (245, 106, 106, 3, 5);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (246, 107, 101, 2, 4);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (247, 107, 107, 5, 9);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (248, 108, 65, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (249, 108, 108, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (250, 109, 96, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (251, 109, 109, 3, 6);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (252, 110, 65, 0, 2);
INSERT IGNORE INTO example_sentence_words (id, example_sentence_id, word_id, start_index, end_index) VALUES (253, 110, 110, 6, 9);

-- ============================================================
-- 딕테이션(듣고 받아쓰기) 전용 문장. domain/example의 단어별 예문과는 별개.
-- ============================================================
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (1, 'おはようございます。', 'おはようございます。', '좋은 아침입니다.', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (2, '今日は天気がいいですね。', 'きょうはてんきがいいですね。', '오늘은 날씨가 좋네요.', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (3, 'これは私の本です。', 'これはわたしのほんです。', '이것은 제 책입니다.', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (4, 'すみません、駅はどこですか。', 'すみません、えきはどこですか。', '실례합니다, 역은 어디예요?', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (5, '私は毎朝お茶を飲みます。', 'わたしはまいあさおちゃをのみます。', '저는 매일 아침 차를 마셔요.', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (6, '明日は友達と映画を見ます。', 'あしたはともだちとえいがをみます。', '내일은 친구와 영화를 봐요.', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (7, '昨日は雨が降りました。', 'きのうはあめがふりました。', '어제는 비가 내렸어요.', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (8, '今からご飯を食べます。', 'いまからごはんをたべます。', '지금부터 밥을 먹을게요.', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (9, '週末は家でゆっくり休みます。', 'しゅうまつはいえでゆっくりやすみます。', '주말은 집에서 느긋하게 쉬어요.', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (10, '夜遅くまで勉強しました。', 'よるおそくまでべんきょうしました。', '밤 늦게까지 공부했어요.', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (11, 'もう少し大きい声で話してください。', 'もうすこしおおきいこえではなしてください。', '조금 더 큰 목소리로 말해주세요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (12, '今度の休みに旅行に行きたいです。', 'こんどのやすみにりょこうにいきたいです。', '이번 휴가에 여행을 가고 싶어요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (13, '電車が遅れて会議に遅刻しました。', 'でんしゃがおくれてかいぎにちこくしました。', '전철이 늦어서 회의에 지각했어요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (14, '難しい問題でしたが、最後まで頑張りました。', 'むずかしいもんだいでしたが、さいごまでがんばりました。', '어려운 문제였지만 끝까지 열심히 했어요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (15, 'この道をまっすぐ行くと図書館があります。', 'このみちをまっすぐいくととしょかんがあります。', '이 길을 곧장 가면 도서관이 있어요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (16, '忙しくても毎日運動するようにしています。', 'いそがしくてもまいにちうんどうするようにしています。', '바쁘더라도 매일 운동하도록 하고 있어요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (17, '約束の時間に間に合わなくて困りました。', 'やくそくのじかんにまにあわなくてこまりました。', '약속 시간에 맞추지 못해서 곤란했어요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (18, '先生に分からないところを聞きました。', 'せんせいにわからないところをききました。', '선생님께 모르는 부분을 물었어요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (19, '引っ越しの準備で毎日忙しいです。', 'ひっこしのじゅんびでまいにちいそがしいです。', '이사 준비로 매일 바빠요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (20, '天気予報によると、明日は雪が降るそうです。', 'てんきよほうによると、あしたはゆきがふるそうです。', '일기예보에 따르면 내일은 눈이 온다고 해요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (21, '経済の状況が悪くなっているため、就職が難しくなっている。', 'けいざいのじょうきょうがわるくなっているため、しゅうしょくがむずかしくなっている。', '경제 상황이 나빠지고 있어서 취업이 어려워지고 있다.', 'N3', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (22, '彼は失敗を繰り返しながらも諦めずに挑戦を続けた。', 'かれはしっぱいをくりかえしながらもあきらめずにちょうせんをつづけた。', '그는 실패를 반복하면서도 포기하지 않고 도전을 계속했다.', 'N3', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (23, '環境を守るために、私たちにできることは何でしょうか。', 'かんきょうをまもるために、わたしたちにできることはなんでしょうか。', '환경을 지키기 위해 우리가 할 수 있는 일은 무엇일까요.', 'N3', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (24, '一度決めたことは最後まで責任を持ってやり遂げたい。', 'いちどきめたことはさいごまでせきにんをもってやりとげたい。', '한번 정한 일은 끝까지 책임을 지고 해내고 싶다.', 'N3', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (25, '忙しい日々の中でも、家族との時間を大切にしている。', 'いそがしいひびのなかでも、かぞくとのじかんをたいせつにしている。', '바쁜 나날 속에서도 가족과의 시간을 소중히 하고 있다.', 'N3', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (26, '名前は何ですか。', 'なまえはなんですか。', '이름이 무엇인가요?', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (27, '誕生日はいつですか。', 'たんじょうびはいつですか。', '생일이 언제예요?', 'N5', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (28, 'この漢字はどう読みますか。', 'このかんじはどうよみますか。', '이 한자는 어떻게 읽나요?', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (29, '頭が痛いので、今日は早く帰ります。', 'あたまがいたいので、きょうははやくかえります。', '머리가 아파서 오늘은 일찍 돌아가요.', 'N4', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (30, '相手の立場になって考えることが大切だと思う。', 'あいてのたちばになってかんがえることがたいせつだとおもう。', '상대방의 입장이 되어 생각하는 것이 중요하다고 생각한다.', 'N3', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (31, '努力すれば必ず結果が出るとは限らない。', 'どりょくすればかならずけっかがでるとはかぎらない。', '노력하면 반드시 결과가 나온다고는 할 수 없다.', 'N3', NOW());
INSERT IGNORE INTO dictation_sentences (id, sentence_jp, sentence_reading, sentence_meaning, level, created_at) VALUES (32, '今日はとても楽しい一日でした。', 'きょうはとてもたのしいいちにちでした。', '오늘은 매우 즐거운 하루였어요.', 'N5', NOW());
